# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'bitcamp2018' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bitcamp2018
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  target 'bitcamp2018-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bitcamp2018Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
